### ISSUE TITLE
Different ruby versions

### ISSUE THREAD

**Issue by Kishaihd** [tresacton/dspectrumgui#10]
When I run 
`bundle`
i get the following output in orange (warning?):
`Your Gemfile lists the gem guard-rspec (>= 0) more than once.
You should probably keep only one of them.
While it's not a problem now, it could cause errors if you change the version of one of them later.`
And the last line in red:
`Your Ruby version is 2.4.1, but your Gemfile specified 2.2.2`
And nothing further happens.

I manually changed the version specified in the Gemfile to 2.4.1, but that led down a rabbit hole of manually changing several version numbers, and that ultimately didn't work out.

Any insight into this? Do I have to downgrade my version of ruby installed to 2.2.2?

**Comment by tresacton** [comment]
you can try running it on 2.4.1 by changing the version number in the Gemfile and in the .ruby-version file, but ymmv. I recommend sticking to ruby 2.2.x. you can keep 2.4.1 and install 2.2.2 using RVM as detailed in the instruction guide and they wont interfere with each other. when you are in the dspectrumgui directory, rvm will notice and set your active ruby version to 2.2.2 while you are there.

Thanks for passing on the twice-listed gems, I'll correct that - it doesnt affect functionality though and is not contributing to your issue.

**Comment by tresacton** [comment]
I'm going to close this for now. Feel free to re-open if you have any further installation issues.
