### ISSUE TITLE
rake db:migrate failing - Causes broken install

### ISSUE THREAD

**Issue by flayisflay** [tresacton/dspectrumgui#12]
### Issue Type
[bug]

### Actual Behaviour
Proceeding with the installation results in an install which fails upon the first GET

rake db:migrate fails with "`last_comment` is deprecated. Please use `last_description` instead"

This seems to be due to an out of date version of respec.

I ran `bundle update rspec rspec-rails` and reinstalled through the current instructions.

Worked fine.

### What commit were you running? 

(Go to your DSpectrumGUI app, and click "About", and paste the relevant information from the  You are currently running: v0.1.1-beta-32-gf4d736e || f4d736e733b3b5d3aa4df4f490d60bccb34d6ccf

**Comment by tresacton** [comment]
can you please post the output of `rvm list`

**Comment by tresacton** [comment]
I'm closing this issue for the moment as its been a few months. If you are still experiencing this problem, please update this ticket.
