### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by mike65535** [tresacton/dspectrumgui#16]
I've been using dspectrumgui for several months on a laptop.  Just updated to a new laptop and have tried to install dspectrumgui

1) After running the very first steps here:

```
Installing RVM & Ruby 2.2.8
.
.
.
source /etc/profile.d/rvm.sh
echo "source /etc/profile.d/rvm.sh" >> ~/.bashrc
```

I now get an error at boot indicating that bash cannot find rvm.sh

2.  When I run    `rails s -p 3001`    I get 

```
Ignoring executable-hooks-1.5.0 because its extensions are not built. Try: gem pristine executable-hooks --version 1.5.0
Ignoring gem-wrappers-1.4.0 because its extensions are not built. Try: gem pristine gem-wrappers --version 1.4.0
Traceback (most recent call last):
	2: from /usr/bin/rails:23:in `<main>'
	1: from /usr/share/rubygems/rubygems.rb:308:in `activate_bin_path'
/usr/share/rubygems/rubygems.rb:289:in `find_spec_for_exe': can't find gem railties (>= 0.a) with executable rails (Gem::GemNotFoundException)
```

**Comment by tresacton** [comment]
Hi Mike,

Regarding your first issue, open a terminal and run:
```source /home/nullwolf/.rvm/scripts/rvm```

If that works fine without any errors, then replace the line you echoed into your ~/.bashrc file with the line above. Let me know if it did error, and also include the output of the command that installs RVM and I'll help you further.

After the above is sorted out, try to follow all of the installation steps again before you attempt to start the rails server (i.e. everything after the ```echo "source /etc/profile.d/rvm.sh" >> ~/.bashrc``` line).

If the server still doesn't start at that stage, then please reply here with the output of the following commands and I'll see what I can do to help you out.

1. run ```rvm list``` and post the output here
2. run ```bundle install``` and post the output here
3. run ```rails s -p 301``` and post the output  here

**Comment by tresacton** [comment]
[no response. closing issue for the moment. if you haven't resolved this then please reopen with output requested above.]
