### ISSUE TITLE
File Recording Option not showing up in GUI

### ISSUE THREAD

**Issue by udaydatrak** [tresacton/dspectrumgui#17]
### Issue Type
when I run this command #OSMOCOM_FFT, Its opening up GUI as shown in documentation but not showing one major option 'FILE Recording"

### Expected Behaviour
File recording option is not showing up in osmocomm
![uday_12nov](https://user-images.githubusercontent.com/19525644/48343365-34336100-e698-11e8-8111-7eca5b0f9a9e.png)

### Actual Behaviour
What happened instead?

### What commit were you running? 
(Go to your DSpectrumGUI app, and click "About", and paste the relevant information from the "Application Status Section" here)

**Comment by tresacton** [comment]
Hi there,

This isn't an issue with DSpectrumGUI I'm afraid. This is another tool and is used for taking captures, it is separate to this application. It looks as though this is an issue with your display resolution, but I can't tell if that's your entire screen or if that's just where you've cropped the image. 

I'd recommend playing with your display settings, trying to connect to a larger external monitor, and if those fail, then submitting an issue in https://github.com/osmocom/gr-osmosdr 

Good luck, I hope you reach a resolution.
