### ISSUE TITLE
Error while installing ruby 2.2.8

### ISSUE THREAD

**Issue by blopblopblup** [tresacton/dspectrumgui#18]
### Issue Type
[bug]

When installing ruby with RVM I get this error : 

Warning, new version of rvm available '1.29.7', you are using older version '1.29.7-next'.
You can disable this warning with:    echo rvm_autoupdate_flag=0 >> ~/.rvmrc
You can enable  auto-update  with:    echo rvm_autoupdate_flag=2 >> ~/.rvmrc
Searching for binary rubies, this might take some time.
No binary rubies available for: kali/kali-rolling/x86_64/ruby-2.2.8.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for kali.
Removing undesired packages: libssl-dev, libssl1.1...
Error running 'requirements_debian_libs_remove libssl-dev libssl1.1',
please read /usr/local/rvm/log/1554107365_ruby-2.2.8/package_remove_libssl-dev_libssl1.1.log
Requirements installation failed with status: 100.

I am running the latest VMware kali.

**Comment by tresacton** [comment]
I think the ruby version in use is due for an upgrade. As an interim measure you may be able to bump up the minor / patch level of the ruby version in the app. You can do way by editing both the Gemfile and the .rvmrc file (make sure the versions match though). And then continue the instructions starting with the bundle command.

Sorry for the delayed response. I've had some personal crisises to attend to recently. 

In the next couple of weeks I plan to upgrade the application.

**Comment by tresacton** [comment]
hey there.

I finally found the time to bump up the versions a bit.

I'm closing this issue, but you're welcome to reopen it if your problem persists despite the upgrade of rails/ruby versions.
